@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь умного дома")
Person(user2, "Пользователь", "Пользователь умного дома")

System(sensor, "Sensor", "Датчик")
System(sensor2, "Sensor2", "Датчик 2")
System(SmartHomeSystem, "Умный дом", "Веб-интерфейс, организует удалённое управление отоплением в доме")

System_Ext(api, "SmartHome API", "API управлением умного датчиком, регистрацией датчиков")

Rel(user, SmartHomeSystem, "Устанавливает значение")
Rel(user2, SmartHomeSystem, "Устанавливает значение")
Rel(SmartHomeSystem,api,"")
Rel(api,SmartHomeSystem,"Обмен данными")
Rel(api,sensor,"Отправка данных")
Rel(api,sensor2,"Отправка данных")

@enduml