@startuml
title SmartHome Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь умного дома")
System(SmartHomeSystem, "Умный дом", "Система организует удалённое управление отоплением в доме")

System_Ext(api, "SmartHome API", "API управлением умного дома")

Rel(user, SmartHomeSystem, "Просматривает температуру/управляет датчиками")
Rel(SmartHomeSystem,api,"Получение данных")

@enduml