@startuml
title SmartHome Gateway Management Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class Gateway {
  +User user_info
  +Home home_info
  +List<Scenario> scenarios
  +List<Device> devices
  +void getDevices()
  +void getScenario()
  +void getHomeInfo()
  +void setEventTemp()
  +void setEventSensor()
  +void setEventLighter()
  +void checkToken()
}

@enduml