@startuml
title SmartHome Gateway Management Code Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class Gateway {
  +User user_info
  +Home home_info
  +List<Scenario> scenarios
  +List<Device> devices
  +void getDevices()
  +void getScenario()
  +void getHomeInfo()
  +void setEventTemp()
  +void setEventSensor()
  +void setEventLighter()
  +void checkToken()
}

class Scenario {
  +String id
  +String name
  +Time dt_create
  +Time dt_update
  +String status
  +List<Module> modules
}

class Module {
  +String id
  +String name
  +String status
  +String value
  +String description
  +String location
  +Time dt_create 
  +List<Device> devices
}

class Device {
  +String id
  +String name
  +DeviceType type_id
  +String serial_number
  +TelemetryData params
  +String status
}

Gateway "1" -- "0..*" Scenario : includes
Scenario "1" -- "0..*" Module : includes
Module "1" -- "0..*" Device : includes

@enduml