@startuml
title SmartHome Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "Пользователь", "Пользователь системы умный дом")
System(SmartHomeSystem, "SmartHome System", "Система управлением умным домом")
System(sensor, "Sensor", "Датчик температуры")
System(lighter, "Lighter", "Люстра")

Container_Boundary(SmartHomeSystem, "SmartHome System") {
  Container(WebApp, "Веб-интерфейс", "JavaScript", "Взаимодействие с пользователем")
  Container(MobileApp, "Моб.приложение", "Kotlin, Swift", "Взаимодействие с пользователем")
  Container(AuthApi, "Keycloak Auth", "Авторизация")
  Container(BffWebApi, "BFF Service", "Golang", "Обмен данными с фронтом")
  Container(BffMobileApi, "BFF Service", "Golang", "Обмен данными с фронтом")
  Container(tempApi, "Temperature Service", "Golang", "Получение данных по температуре")
  Container(sensorApi, "Sensor Service", "Golang", "Получение данных с датчика")
  Container(lightingApi, "Lighting Service", "Golang", "Получение данных с датчика")
  Container(Database, "Database", "PostgreSQL", "Данные о доме")
}

System_Ext(AuthApi, "Keycloak Auth", "API Авторизации")
System_Ext(BffWebApi, "BFF Web", "API для работы с веб-интерфейсом")
System_Ext(BffMobileApi, "BFF Mobile", "API для работы с моб.интерфейсами")
System_Ext(tempApi, "Tempereture API", "API управлением температуры")
System_Ext(sensorApi, "Sensor API", "API управлением датчика")
System_Ext(lightingApi, "Lighting API", "API управлением светом")

Rel(user, WebApp, "Использует веб-интерфейс")
Rel(user, MobileApp, "Использует приложение")

Rel(WebApp, AuthApi, "Авторизация")
Rel(MobileApp, AuthApi, "Авторизация")

Rel(AuthApi, BffWebApi, "Обмен данными с BFF")
Rel(AuthApi, BffMobileApi, "Обмен данными с BFF")

Rel(BffWebApi,tempApi,"Управление температурой")
Rel(BffWebApi,sensorApi,"Управление сенсорами")
Rel(BffWebApi,lightingApi,"Управление светом")

Rel(BffMobileApi,tempApi,"Управление температурой")
Rel(BffMobileApi,sensorApi,"Управление сенсорами")
Rel(BffMobileApi,lightingApi,"Управление светом")

Rel(tempApi,Database,"Получение данных")
Rel(sensorApi,Database,"Получение данных")
Rel(lightingApi,Database,"Получение данных")

Rel(sensorApi,sensor,"Отправка данных сенсору")
Rel(lightingApi, lighter,"Отправка данных на люстру")

@enduml